site_name: Coronavírus Brasil - Material
theme:
  name: material
markdown_extensions:
  - footnotes
repo_url: https://github.com/coronablogbr/material
repo_name: coronablogbr/material
nav:
  - "Sobre": index.md
  - colabore.md
  - aplicativos.md
  - artigos-cientificos.md
  - ferramentas.md
  - fontes-de-dados.md
  - Fontes de Informações:
    - sites.md
    - podcasts.md
    - youtube.md
  - leituras.md
  - Medicamentos:
    - Cloroquina: cloroquina.md
  - fake-news.md
  - perguntas-e-respostas.md
  - prevencao.md
  - projetos-coletivos.md
  - saude-mental.md
  - terminologia.md
  - Vacinas:
    - "Bacille Calmette-Guérin (BCG)": vacina-bcg.md